language: scala
services: docker
before_install:
  - docker run -d -p 127.0.0.1:5672:5672 --hostname localhost --name some-rabbit rabbitmq:3
scala:
  - 2.12.7
jdk:
  - oraclejdk8
script:
  - sbt test
  - sbt ";++ 2.11.11 test"
  - sbt ";++ 2.10.7 test"
